### ISSUE TITLE
Log File acces error

### ISSUE THREAD

**Issue by GamerClassN7** [GamerClassN7/HA_Desktop_Companion#84]
### Describe the Bug
```
[07.25.2024-19:33.49][0]Initializing
[07.25.2024-19:33.49][3][HADC_REBORN]System.I[07.25.2024-19:33.49][3][HADC_REBORN]System.IO.IOException: The process cannot access the file 'C:\Users\ddd\Downloads\HA_Self_Contained\logs\log_07_25_2024.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
[07.25.2024-19:33.49][0]NAMESPACE root\CIMV2
 Win32_LogicalDisk[0]
[07.25.2024-19:33.49][0]SELECT FreePhysicalMemory FROM Win32_OperatingSystem[0]
: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\ddd\Downloads\HA_Self_Contained\logs\log_07_25_2024.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at HADC_REBORN.Class.Helpers.Logger.initialize() in C:\Users\Docker\Documents\GitHub\HA_Desktop_Companion\HADC_REBORN\Class\Helpers\Logger.cs:line 57
   at HADC_REBORN.Class.Helpers.Logger.writeLine(String msg, Int32 type) in C:\Users\Docker\Documents\GitHub\HA_Desktop_Companion\HADC_REBORN\Class\Helpers\Logger.cs:line 97
   at HADC_REBORN.Class.Sensors.Wmic.GetValue(String wmic_class, String wmic_selector, String wmic_namespace, Int32 wmic_iterator_index) in C:\Users\Docker\Documents\GitHub\HA_Desktop_Companion\HADC_REBORN\Class\Sensors\Wmic.cs:line 58
   at InvokeStub_Wmic.GetValue(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[07.25.2024-19:33.49][0]ITERATOR 0
[07.25.2024-19:33.49][3][HADC_REBORN]System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\ddd\Downloads\HA_Self_Contained\logs\log_07_25_2024.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at HADC_REBORN.Class.Helpers.Logger.initialize() in C:\Users\Docker\Documents\GitHub\HA_Desktop_Companion\HADC_REBORN\Class\Helpers\Logger.cs:line 57
   at HADC_REBORN.Class.Helpers.Logger.writeLine(String msg, Int32 type) in C:\Users\Docker\Documents\GitHub\HA_Desktop_Companion\HADC_REBORN\Class\Helpers\Logger.cs:line 97
   at HADC_REBORN.Class.Sensors.Wmic.GetValue(String wmic_class, String wmic_selector, String wmic_namespace, Int32 wmic_iterator_index) in C:\Users\Docker\Documents\GitHub\HA_Desktop_Companion\HADC_REBORN\Class\Sensors\Wmic.cs:line 58
   at InvokeStub_Wmic.GetValue(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[07.25.2024-19:33.49][0]OUTPUT: 3315691520
[07.25.2024-19:33.49][0]OUTPUT: 15053644
[07.25.2024-19:33.49][3][HADC_REBORN]System.UnauthorizedAccessException: Access to the path 'C:\Users\ddd\Downloads\HA_Self_Contained\logs\log_07_22_2024.log' is denied.
```

### Steps to Reproduce

just log ower the midnight 

### Expected Behaviour

no error

### Version

0.0.0.0

**Comment by GamerClassN7** [comment]
Fixed in dev
